# default config.yml for CreativeNbtControl
# config version 1.13
 

#The plugin will check for the following items.
# Material names: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Material.html
EnabledFor:
- 'CHEST'
- 'TRAPPED_CHEST'
- 'FURNACE'
- 'DROPPER'
- 'DISPENSER'
- 'HOPPER'
- 'JUKEBOX'
- 'BREWING_STAND_ITEM'
- 'BEACON'
- 'SIGN'
- 'SKULL_ITEM'
- 'MONSTER_EGG'
- 'COMMAND'
- 'MOB_SPAWNER'
#For 1.8, 1.9 and 1.10
- 'BANNER'
#For 1.11 and 1.12
- 'BURNING_FURNACE'
- 'COMMAND_CHAIN'
- 'COMMAND_MINECART'
- 'COMMAND_REPEATING'
- 'BLACK_SHULKER_BOX'
- 'BLUE_SHULKER_BOX'
- 'BROWN_SHULKER_BOX'
- 'CYAN_SHULKER_BOX'
- 'GRAY_SHULKER_BOX'
- 'GREEN_SHULKER_BOX'
- 'LIGHT_BLUE_SHULKER_BOX'
- 'LIME_SHULKER_BOX'
- 'MAGENTA_SHULKER_BOX'
- 'ORANGE_SHULKER_BOX'
- 'PINK_SHULKER_BOX'
- 'PURPLE_SHULKER_BOX'
- 'RED_SHULKER_BOX'
- 'SILVER_SHULKER_BOX'
- 'WHITE_SHULKER_BOX'
- 'YELLOW_SHULKER_BOX'
#For 1.13 API
- 'BREWING_STAND'
- 'LEGACY_BREWING_STAND'
- 'LEGACY_BREWING_STAND_ITEM'
- 'LEGACY_SKULL'
- 'PLAYER_HEAD'
- 'LEGACY_MONSTER_EGG'
- 'LEGACY_MONSTER_EGGS'
- 'COMMAND_BLOCK'
- 'LEGACY_MOB_SPAWNER'
- 'SPAWNER'
- 'LEGACY_BURNING_FURNACE'
- 'CHAIN_COMMAND_BLOCK'
- 'REPEATING_COMMAND_BLOCK'
- 'LEGACY_COMMAND'
- 'LEGACY_COMMAND_CHAIN'
- 'LEGACY_COMMAND_MINECART'
- 'LEGACY_COMMAND_REPEATING'
- 'SHULKER_BOX'
- 'BLACK_SHULKER_BOX'
- 'BLUE_SHULKER_BOX'
- 'BROWN_SHULKER_BOX'
- 'CYAN_SHULKER_BOX'
- 'GRAY_SHULKER_BOX'
- 'GREEN_SHULKER_BOX'
- 'LIGHT_BLUE_SHULKER_BOX'
- 'LIME_SHULKER_BOX'
- 'MAGENTA_SHULKER_BOX'
- 'ORANGE_SHULKER_BOX'
- 'PINK_SHULKER_BOX'
- 'PURPLE_SHULKER_BOX'
- 'RED_SHULKER_BOX'
- 'SILVER_SHULKER_BOX'
- 'WHITE_SHULKER_BOX'
- 'YELLOW_SHULKER_BOX'
- 'LEGACY_BLACK_SHULKER_BOX'
- 'LEGACY_BLUE_SHULKER_BOX'
- 'LEGACY_BROWN_SHULKER_BOX'
- 'LEGACY_CYAN_SHULKER_BOX'
- 'LEGACY_GRAY_SHULKER_BOX'
- 'LEGACY_GREEN_SHULKER_BOX'
- 'LEGACY_LIGHT_BLUE_SHULKER_BOX'
- 'LEGACY_LIME_SHULKER_BOX'
- 'LEGACY_MAGENTA_SHULKER_BOX'
- 'LEGACY_ORANGE_SHULKER_BOX'
- 'LEGACY_PINK_SHULKER_BOX'
- 'LEGACY_PURPLE_SHULKER_BOX'
- 'LEGACY_RED_SHULKER_BOX'
- 'LEGACY_SILVER_SHULKER_BOX'
- 'LEGACY_WHITE_SHULKER_BOX'
- 'LEGACY_YELLOW_SHULKER_BOX'
#For 1.14 API
- 'BARREL'
- 'BLAST_FURNACE'
- 'SMOKER'
#For 1.15 API
- 'BEE_NEST'
- 'BEEHIVE'
- 'POTION'
- 'SPLASH_POTION'
- 'LINGERING_POTION'


#Chat messages with color and format codes support.
#Minecraft Color and Format Codes: http://minecraft.gamepedia.com/Formatting_codes    
ChatMessages:
    NoPermission: '&4[System] &cYou don''t have permission!'
    CmdHelp: '&4[System] &cAvailable commands:&6 /cnc reload'
    CmdReload: '&2[System] &aConfig reload complete!'
    OpenSurvivalFrame: '&6[System] &eYou must be in survival mode to place an item in a frame!'
    OpenSurvivalArmor: '&6[System] &eYou must be in survival mode to place items in an armor stand!'
